### ISSUE TITLE
Duplicate Jenkins project

### ISSUE THREAD

**Issue by logological** [UKPLab/lrec2016-ubyline#6]
On the zoidberg Jenkins server, there are two separate build projects for the lrec2016-ubyline documentation.  One of them is named [Ubyline-Lrec2016 Doc](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/Ubyline-Lrec2016%20Doc/) and seems to be in use, and the other is named [Ubyline-Lrec2016 Documentation](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/Ubyline-Lrec2016%20Documentation/) and does not seem to be in use.

Is this second build project actually being used for anything, or can it be deleted?

**Comment by MedKhem** [comment]
The second could be deleted. This was a due to a problem with the server, as far as I remember

**Comment by logological** [comment]
OK, I've deleted it.
